apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    rc: nginx-rc
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-rc-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
